### ISSUE TITLE
text: Section 2.1

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/gambly#1]
Text from 2nd paragraph of Section 2.1: 
> In the context of Subhalo-Abundance matching modeling, accuracy of which depends on subhalo completeness especially in the low mass limit, the SMDP simulation has been used to model the faintest galaxy samples in the SDSS data (see Guo et al. (2016)).

It's unclear what you mean by "accuracy" in this context. Do you mean that to extend AMing reliably to lower mass halos, a high resolution simulation that is complete at low masses is necessary. 

Note, this was *not* brought up by the referee but I think is an important to address.

**Comment by mjvakili** [comment]
I agree that this is vaguely worded. 
I am referring to AMing methods that use mass proxies other than halo mass such as Vmax, Vpeak, etc.

For low mass halos, halo substructures are poorly resolved and thus it is hard to reliably use AM with these quantities.

**Comment by changhoonhahn** [comment]
OKay. In that case, I think it's important to clarify that you're talking about the reliability of AM in the case of low mass halos rather than talking about accuracy, which I think is misleading. I'll edit it accordingly.
