### ISSUE TITLE
Text Section 2.2: Dutton & Maccio

### ISSUE THREAD

**Issue by changhoonhahn** [mjvakili/gambly#2]
@mjvakili 

First, there's a missing citation in Section. It's marked in dark green in ms.pdf .

In the referee report (**minor comment #3**), the referee refers to Dutton & Maccio relation for concentration. I didn't see this particular citation anywhere in Section 2.2. Is it the missing citation? Also, I think address minor comment #3 will require a bit of thought.

**Comment by mjvakili** [comment]
The concentration now come directly from the halo catalog. So this comment is addressed.
